// src/solid.main.tsx
import { Router } from 'solid-app-router';
import { render } from 'solid-js/web';

import { AppComponent } from './components/app/component';

const htmlDivElement: HTMLDivElement | null = document.querySelector('div#app');
if (htmlDivElement instanceof HTMLDivElement) {
  render(
    () => (
      <Router>
        <AppComponent className="" />
      </Router>
    ),
    htmlDivElement
  );
}

// src/react.main.tsx
import React from 'react';
import ReactDOM from 'react-dom';
import { HashRouter as Router } from 'react-router-dom';

import { AppComponentWithRouter } from './components/app/component';

const htmlDivElement: HTMLDivElement | null = document.querySelector('div#app');
if (htmlDivElement instanceof HTMLDivElement) {
  ReactDOM.render(
    <Router>
      <AppComponentWithRouter />
    </Router>,
    htmlDivElement
  );
}
